
const CardsData = [
    
    {
        id: 1,
        brandname: "Realme",
        modelNumber: "10i",
        ram:"6GB",
        internalStorage:"256GB",
        screenSize:"5.8 inch",
        camera:"64MP Rear Camera, 5MP Front Camera",
        imgdata: "/image/img1.jpg",
        address: "North Indian",
        somedata: " 1175 + order placed from here recently",
        price: "35,000",
        rating: "3.8",
        qnty:0
    },
    {
        id: 2,
        brandname: "Redmi",
        modelNumber: "8A",
        ram:"4GB",
        internalStorage:"128GB",
        screenSize:"5.5 inch",
        camera:"13MP Rear Camera, 5MP Front Camera",
        imgdata: "/image/img2.jpg",
        address: "Pune",
        somedata: " 2525 + order placed from here recently",
        price: "30,000",
        rating: "3.9",
        qnty:0
    },
    {
        id: 3,
        brandname: "OnePlus",
        modelNumber: "10T",
        ram:"12GB",
        internalStorage:"512GB",
        screenSize:"6.5 inch",
        camera:"128MP Rear Camera, 64MP Front Camera",
        imgdata: "/image/img3.jpg",
        address: "Goa",
        somedata: " 650 + order placed from here recently",
        price: "70,000",
        rating: "4.2",
        qnty:0
    },
    {
        id: 4,
        brandname: "Redmi",
        modelNumber: "10A",
        ram:"16GB",
        internalStorage:"512GB",
        screenSize:"6.0 inch",
        camera:"64MP Rear Camera, 32MP Front Camera",
        imgdata: "/image/img4.jpg",
        address: "Bhopal",
        somedata: " 300 + order placed from here recently",
        price: "75,500",
        rating: "3.8",
        qnty:0
    },
    {
        id: 5,
        brandname: "iphone",
        modelNumber: "11",
        ram:"8GB",
        internalStorage:"128GB",
        screenSize:"5.5 inch",
        camera:"128MP Rear Camera, 64MP Front Camera",
        imgdata: "/image/img5.jpg",
        address: "North Indian",
        somedata: "1050 + order placed from here recently",
        price: "80,000",
        rating: "4.0",
        qnty:0
    },
    {
        id: 6,
        brandname: "samsung",
        modelNumber: "8A",
        ram:"16GB",
        internalStorage:"512GB",
        screenSize:"6.5 inch",
        camera:"128MP Rear Camera, 128MP Front Camera",
        imgdata: "/image/img6.jpg",
        address: "Wraps FastFood, Chines",
        somedata: " 1100 + order placed from here recently",
        price: "70,000",
        rating: "3.8",
        qnty:0
    },
    {
        id: 7,
        brandname: "Redmi",
        modelNumber: "9i",
        ram:"6GB",
        internalStorage:"256GB",
        screenSize:"5.8 inch",
        camera:"64MP Rear Camera, 5MP Front Camera",
        imgdata: "/image/img7.jpg",
        address: "North Indian",
        somedata: " 1175 + order placed from here recently",
        price: "45,000",
        rating: "3.8",
        qnty:0
    },
    {
        id: 8,
        brandname: "Techno",
        modelNumber: "9",
        ram:"6GB",
        internalStorage:"256GB",
        screenSize:"5.8 inch",
        camera:"64MP Rear Camera, 5MP Front Camera",
        imgdata: "/image/img8.jpg",
        address: "North Indian",
        somedata: " 1175 + order placed from here recently",
        price: "85,000",
        rating: "3.8",
        qnty:0
    },
    {
        id: 9,
        brandname: "Nothing",
        modelNumber: "1",
        ram:"6GB",
        internalStorage:"256GB",
        screenSize:"5.8 inch",
        camera:"64MP Rear Camera, 5MP Front Camera",
        imgdata: "/image/img9.jpg",
        address: "North Indian",
        somedata: " 1175 + order placed from here recently",
        price: "75,000",
        rating: "3.8",
        qnty:0
    },
    
    
];

export default CardsData;